user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzMxMzk=

session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: eda8f8c4866048373cea8d1550f367efffa0035085226c69d3b08e7cc7fa725b7ae1bd8bbff75933cebc3
  group_id: 210547650


